Report minor tweeks
UNC-Libraries/ml-repo-preingest-processing pull request #21
Opened 2023-09-08 19:54 UTC by RolRodr

PR addresses 4 tickets:

1. [Min/Max column width](https://unclibrary.atlassian.net/browse/BXC-4282):  Changed image column to 25% of table width since there is no convenient way to set min/max within datatables. If requested, I can modify the css to set min/max, but this might do.

2. [Create CSV link](https://unclibrary.atlassian.net/browse/BXC-4283): Created CSV link button next to table toggle button. Each button has a different background for identification. Happy to adjust if requested.

3. [Keybinding to navigate pages](https://unclibrary.atlassian.net/browse/BXC-4284): Added key bindings for left and right arrow keys to move to previous and next page respectively. Can add additional keybindings if requested.

4. [Loading icon](https://unclibrary.atlassian.net/browse/BXC-4285): Added loading icon for initial load and between toggling tables. The loading icon itself still lags a bit after pressing the toggle button, unsure if this can be addressed.

2023-09-11 14:16 UTC, bbpennel requested changes
The key bindings work great!

I'm getting the loading icon on initial page load, but not for other operations like applying filters or sorting by columns (which tend to take my computer about 2 seconds each). Maybe there's a tiny flicker of the icon when toggling modes right as the new content renders. I'm guessing the browser is lagging and not able to render the icon. Did you try enabling the datatables processing indicator? that might cover the sorting/filtering cases
https://datatables.net/reference/option/processing
https://datatables.net/forums/discussion/63919/loading-text-or-icon-when-data-loads

2023-09-21 17:33 UTC, RolRodr commented on create_report.py
> +    csv_url = args.normalized_url+str(args.file_path)
@bbpennel will the reports always come from the reports directory? I'll just go ahead an make '/shared/reports/' the substring used to normalize the path.

2023-09-21 19:18 UTC, bbpennel commented on create_report.py
> +    csv_url = args.normalized_url+str(args.file_path)
I think the report gets generated as a sibling of the input, so it should be at the same path. But its probably fine to look for /shared/reports/, its not going to moved around much.

I guess if the latency ends up being too major of an issue, we could add a server side component.

2023-09-21 20:20 UTC, RolRodr commented on create_report.py
> +    csv_url = args.normalized_url+str(args.file_path)
I believe the latest push should fix the csv url, as well as the spinner issue by giving a slight delay when toggling off while being asynchronous with the table toggles. It won't address the latency issue, however. I'm happy to start working on the server side component.

2023-09-22 13:06 UTC, bbpennel approved these changes

2023-09-22 13:07 UTC, merged