[BXC-4035] Creates a data ColorBarSegmentation Dataset class
UNC-Libraries/ml-repo-preingest-processing pull request #22
Opened 2023-09-11 20:12 UTC by wintere

Creates a ColorBarSegmentationDataset subclass designed for image segmentation rather than classification, to be followed by a segmentation_workflow_service.py to train and evaluate a model with the new image, target mappings.

Rather than return a mage, binary label tuple, the segmentation dataset class returns an image, mask tuple. Masks are initially computed as binary two dimensional arrays of size [H, W] where H, W are the height and width of the original image, then resized using a similar transformation function to the original image to fit into resnet. 

The correctness of masked regions computed by has been tested by visual comparison in addition to the unit tests provided.

2023-09-12 20:42 UTC, bbpennel requested changes
I think this looks good over all from reading, just a few questions and comments.

You mentioned that you removed the code you used to create images for visual comparison. It would be helpful to retain that, perhaps as a utility method that we can use when we need to inspect outcomes (either while coding or when evaluating the results of a trained model).

I'm trying to think through how we would use the labels (from annotations or the eventual model) for cropping. The current setup is capturing the exact coordinates of the color bar annotation rectangle, which is generally 0-2% from the edge of image, so there are often gaps. The "centerCrop" of the image also introduces additional gaps between the color bar region and the edge of the image, as in the example included in the PR description. So we would need to be able to reverse the centerCrop (I assume this is where capturing `image_dimensions` comes into play), and then capture the non-color bar region as a single rectangle by some means.

2023-09-13 16:47 UTC, wintere commented on src/datasets/color_bar_dataset.py
> +    self.image_dimensions = []
In this case, the list didn't populate properly if I added self.image_dimensions = [] to the SegmentationDataset constructor instead.

2023-09-13 16:47 UTC, wintere commented on src/datasets/color_bar_segmentation_dataset.py
> +  def load_labels(self, path_to_labels):
Fixed.

2023-09-13 16:48 UTC, wintere commented on src/datasets/color_bar_segmentation_dataset.py
> +        width, height = (label['width']), (label['height'])
Fixed, this was an artifact of when I converted from the relative measurements from float to integer earlier in the process.

2023-09-13 16:49 UTC, wintere commented
OK, I've added an image/mask tensor displaying helper function and corrected the formatting errors.  The visualize_tensor command as run in the unit tests displays as expected on Windows, but I haven't tested on another OS.

2023-09-13 17:22 UTC, bbpennel commented
The visualize_tensor method seems to work well on macOS. Maybe keep the lines in the test for getting them, but comment them out so it doesn't pop open images every time the test runs?

2023-09-13 18:54 UTC, bbpennel approved these changes

2023-09-13 18:54 UTC, merged